branch-defaults:
  default:
    environment: image-filter-udacity-sa-dev
    group_suffix: null
deploy:
    artifact: ./www/Archive.zip
global:
  application_name: image-filter-udacity-sa
  branch: null
  default_ec2_keyname: udacity-project-2
  default_platform: Node.js
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
